Project 1: false
Project 2: false
Project 3: false
Project 4: false
Project 5: false
Project 6: false
Project 7: false
Project 8: false
Project 9: false
Project 10: false
Project 11: false
Project 12: false
Project 13: false
Project 14: false
Project 15: false
Project 16: true
Project 17: true
Project 18: false
Project 19: true
Project 20: true
Project 21: true
Project 22: true
Project 23: true
Project 24: false
Project 25: false
Project 26: false
Project 27: false
Project 28: true
Project 29: false
Project 30: false
Project 31: false
Project 32: false
Project 33: false
Project 34: false
Project 35: false
Project 36: false
